create table developer(
    id int generated by default as identity primary key,
    first_name varchar(25) not null,
    last_name varchar(25) not null,
    specialty_id int references specialty(id),
    status varchar(7) not null
)